Спринт 9 версия 1.
MoriYandex/java-filmorate pull request #4
Opened 2023-08-03 17:48 UTC by MoriYandex

2023-08-03 19:07 UTC, EugeneLenkevich requested changes
Привет, Мориниллэ, спасибо за PR

В целом все отлично :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-08-03 19:07 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final TreeMap<Integer, Film> allFilms = new TreeMap<>();
В TreeMap держишь чтобы всегда в отсортрованном вие были?

А еще, при желании, можно использовать ConcurrentHashMap. Web - конкурентная среда :)

https://habr.com/ru/post/132884/

Ну и лучше все же вот так 

`private final Map<Integer, Film> allFilms = new TreeMap<>();`

2023-08-03 19:07 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName() == null || film.getName().isBlank()) {
Для проверки строк на пустоту можно использовать 
StringUtils.hasText
или же аналогичную функцию из apache commons 
StringUtils.isNotBlank
=)

2023-08-03 19:07 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() > maxDescriptionLength) {
film.getDescription().length()

Тут бы проверку на null, иначе будем получать ошибки если данных не указано :)

2023-08-03 19:07 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(MIN_RELEASE_DATE)) {
Аналогично :)

2023-08-03 19:07 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info(usersListGotMessage);
А не проще ли сразу писать в лог без дополнительных переменных, в этом особого смысла не уверен что много, но вот код пухнет :) 

log.info( "Получен список всех пользователей.");

2023-08-04 15:16 UTC, MoriYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() > maxDescriptionLength) {
Вставил проверку.

2023-08-04 15:18 UTC, MoriYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(MIN_RELEASE_DATE)) {
Аналогично :)

2023-08-04 15:22 UTC, MoriYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info(usersListGotMessage);
Заменил там, где пишется только в лог.

2023-08-04 15:43 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-08-15 16:50 UTC, merged